#!/bin/bash
set -x
set -u
X=./virtual_x_server

# test all UIs even if one of them fails
FAIL=false
   ./test_ncurses "$@" 2> ncurses.log || FAIL=true
$X ./test_qt      "$@" 2> qt.log      || FAIL=true
$X ./test_gtk     "$@" 2> gtk.log     || FAIL=true

! $FAIL
